name: Release APK

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Install JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Prepare signing keystore
        run: echo "${{ secrets.keystore }}" | base64 -d > ${{ github.workspace }}/signing-key.jks

      - name: Build signed APK
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            assembleFreeRelease
            -Pandroid.injected.signing.store.file=${{ github.workspace }}/signing-key.jks
            -Pandroid.injected.signing.store.password=${{ secrets.keystore_password }}
            -Pandroid.injected.signing.key.alias=${{ secrets.key_alias }}
            -Pandroid.injected.signing.key.password=${{ secrets.key_password }}

      - name: Cleanup signing keystore
        run: rm $GITHUB_WORKSPACE/signing-key.jks

      - name: Release APK
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          files: |
            app/build/outputs/apk/free/release/app-free-release.apk
